import {
  AUSWAHL_HEADER_DETAIL,
  AUSWAHL_HEADER_SUB,
  AUSWAHL_HEADER_TITLE,
} from './marketingCopy';

export const AUSWAHL_TAGLINE = AUSWAHL_HEADER_TITLE;

export const AUSWAHL_SUBLINE = AUSWAHL_HEADER_SUB;

export const AUSWAHL_DETAIL = AUSWAHL_HEADER_DETAIL;

export const AUSWAHL_ONBOARDING = AUSWAHL_HEADER_SUB;
